GELIR_TABLOSU_HESAPLARI = {
    "A. BRÜT SATIŞLAR": {
        "600": "Yurtiçi Satışlar",
        "601": "Yurtdışı Satışlar",
        "602": "Diğer Gelirler",
    },
    "B. SATIŞ İNDİRİMLERİ (-)": {
        "610": "Satıştan İadeler (-)",
        "611": "Satış İskontoları (-)",
        "612": "Diğer İndirimler (-)",
    },
    "C. NET SATIŞLAR": {},
    "D. SATIŞLARIN MALİYETİ (-)": {
        "620": "Satılan Mamuller Maliyeti (-)",
        "621": "Satılan Ticari Mal Maliyeti (-)",
        "622": "Satılan Hizmet Maliyeti (-)",
        "623": "Diğer Satışların Maliyeti (-)",
    },
    "BRÜT SATIŞ KARI VEYA ZARARI": {},
    "E. FAALİYET GİDERLERİ (-)": {
        "630": "Araştırma ve Geliştirme Giderleri (-)",
        "631": "Pazarlama, Satış ve Dağıtım Giderleri (-)",
        "632": "Genel Yönetim Giderleri (-)",
    },
    "FAALİYET KARI VEYA ZARARI": {},
    "F. DİĞER FAALİYETLERDEN OLAĞAN GELİR VE KARLAR": {
        "640": "İştiraklerden Temettü Gelirleri",
        "641": "Bağlı Ortaklıklardan Temettü Gelirleri",
        "642": "Faiz Gelirleri",
        "643": "Komisyon Gelirleri",
        "644": "Konusu Olmayan Karşılıklar",
        "645": "Menkul Kıymet Satış Karları",
        "646": "Kambiyo Karları",
        "647": "Reeskont Faiz Gelirleri",
        "648": "Enflasyon Düzeltmesi Karları",
        "649": "Diğer Olağan Gelir ve Karlar",
    },
    "G. DİĞER FAALİYETLERDEN OLAĞAN GİDERLER VE ZARARLAR (-)": {
        "653": "Komisyon Giderleri (-)",
        "654": "Karşılık Giderleri (-)",
        "655": "Menkul Kıymet Satış Zararları (-)",
        "656": "Kambiyo Zararları (-)",
        "657": "Reeskont Faiz Giderleri (-)",
        "658": "Enflasyon Düzeltmesi Zararları (-)",
        "659": "Diğer Olağan Gider ve Zararlar (-)",
    },
    "G. FİNANSMAN GİDERLERİ (-)": {
        "660": "Kısa Vadeli Borçlanma Giderleri (-)",
        "661": "Uzun Vadeli Borçlanma Giderleri (-)",
    },
    "OLAĞAN KAR VEYA ZARAR": {},
    "I. OLAĞANDIŞI GELİR VE KARLAR": {
        "671": "Önceki Dönem Gelir ve Karları",
        "679": "Diğer Olağandışı Gelir ve Karlar",
    },
    "J. OLAĞANDIŞI GİDER VE ZARARLAR": {
        "680": "Çalışmayan Kısım Gider ve Zararları (-)",
        "681": "Önceki Dönem Gider ve Zararları (-)",
        "689": "Diğer Olağandışı Gider ve Zararlar (-)",
    },
    "DÖNEM KARI VEYA ZARARI": {},
    "K. DÖNEM KARI, VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIĞI": {},
    "DÖNEM NET KARI VEYA ZARARI": {},
}
