# Bilanço kalemlerini önceden tanımla (aktif-pasif)
BILANCO_HESAPLARI = {
    "AKTİF": {
        "I. Dönen Varlıklar": {
            "A. Hazır Değerler": {
                "100": "1. Kasa",
                "101": "2. Alınan Çekler",
                "102": "3. Bankalar",
                "103": "4. Veri. Çek. ve Ödeme Emirleri (-)",
                "108": "5. Diğer Hazır Değerler"
            },
            "B. Menkul Kıymetler": {
                "110": "1. Hisse Senetleri",
                "111": "2. Özel Kesim Tahvil ,Sen. ve Bonoları",
                "112": "3. Kamu Kesimi Tahvil , Sen. ve Bono.",
                "118": "4. Diğer Menkul Kıymetler",
                "119": "5. Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)",
            },
            "C. Ticari Alacaklar": {
                "120": "1. Alıcılar",
                "121": "2. Alacak Senetleri",
                "122": "3. Alacak Senetleri Reeskontu (-)",
                "124": "4. Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)",
                "126": "5. Verilen Depozito ve Teminatlar",
                "127": "6. Diğer Ticari Alacaklar",
                "128": "7. Şüpheli Ticari Alacaklar",
                "129": "8. Şüpheli Ticari Alacaklar Karşılığı (-)",
            },
            "D. Diğer Alacaklar": {
                "131": "1. Ortaklardan Alacaklar",
                "132": "2. İştiraklerden Alacaklar",
                "133": "3. Bağlı Ortaklıklardan Alacaklar",
                "135": "4. Personelden Alacaklar",
                "136": "5. Diğer Çeşitli Alacaklar",
                "137": "6. Diğer Alacak Senetleri Reeskontu (-)",
                "138": "7. Şüpheli Diğer Alacaklar",
                "139": "8. Şüpheli Diğer Alacaklar Karşılığı (-)",
            },
            "E. Stoklar": {
                "150": "1. İlk Madde ve Malzeme",
                "151": "2. Yarı Mamuller - Üretim",
                "152": "3. Mamuller",
                "153": "4. Ticari Mallar",
                "157": "5. Diğer Stoklar",
                "158": "6. Stok Değer Düşüklüğü Karşılığı (-)",
                "159": "7. Verilen Sipariş Avansları",
            },
            "F. Yıllara Yaygın İnşaat ve Onarım Maliyetleri": {
                "170": "1. Yıllara Yaygın İnşaat ve Onarım Maliyetleri",
                "178": "2. Yıllara Yaygın İnşaat Enflasyon Düzeltme",
                "179": "3. Taşeronlara Verilen Avanslar",
            },
            "G. Gelecek Aylara Ait Giderler ve Gelir Tahakkukları": {
                "180": "1. Gelecek Aylara Ait Giderler",
                "181": "2. Gelir Tahakkukları",
            },
            "H. Diğer Dönen Varlıklar": {
                "190": "1. Devreden KDV",
                "191": "2. İndirilecek KDV",
                "192": "3. Diğer KDV",
                "193": "4. Peşin Ödenen Vergiler ve Fonlar",
                "195": "5. İş Avansları",
                "196": "6. Personel Avansları",
                "197": "7. Sayım ve Tesellüm Noksanlar",
                "198": "8. Diğer Çeşitli Dönen Varlıklar",
                "199": "9. Diğer Dönen Varlıklar Karşılığı (-)",
            },
        },
        "II. DURAN VARLIKLAR": {
            "A. Ticari Alacaklar": {
                "220": "1. Alıcılar",
                "221": "2. Alacak Senetleri",
                "222": "3. Alacak Senetleri Reeskontu (-)",
                "224": "4. Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)",
                "226": "5. Verilen Depozito ve Teminatlar",
                "229": "6. Şüpheli Alacaklar Karşılığı (-)",
            },
            "B. Diğer Alacaklar": {    
                "231": "1. Ortaklardan Alacaklar",
                "232": "2. İştiraklerden Alacaklar",
                "233": "3. Bağlı Ortaklıklardan Alacaklar",
                "235": "4. Personelden Alacaklar",
                "236": "5. Diğer Çeşitli Alacaklar",
                "237": "6. Diğer Alacak Senetleri Reeskontu (-)",
                "239": "7. Şüpheli Diğer Alacaklar Karşılığı (-)",
            },
            "C. Mali Duran Varlıklar": {    
                "240": "1. Bağlı Menkul Kıymetler",
                "241": "2. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)",
                "242": "3. İştirakler",
                "243": "4. İştiraklere Sermaye Taahhütleri (-)",
                "244": "5. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)",
                "245": "6. Bağlı Ortaklıklar",
                "246": "7. Bağlı Ortaklıklar Sermaye Taahhütleri (-)",
                "247": "8. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)",
                "248": "9. Diğer Mali Duran Varlıklar",
                "249": "10. Diğer Mali Duran Varlıklar Karşılığı (-)",
            },
            "D. Maddi Duran Varlıklar": {
                "250": "1. Arazi ve Arsalar",
                "251": "2. Yeraltı ve Yerüstü Düzenleri",
                "252": "3. Binalar",
                "253": "4. Tesis, Makine ve Cihazlar",
                "254": "5. Taşıtlar",
                "255": "6. Demirbaşlar",
                "256": "7. Diğer Maddi Duran Varlıklar",
                "257": "8. Birikmiş Amortismanlar (-)",
                "258": "9. Yapılmakta Olan Yatırımlar",
                "259": "10. Verilen Avanslar",
            },
            "E. Maddi Olmayan Duran Varlıklar": {
                "260": "1. Haklar",
                "261": "2. Şerefiye",
                "262": "3. Kuruluş ve Örgütlenme Giderleri",
                "263": "4. Araştırma ve Geliştirme Giderleri",
                "264": "5. Özel Maliyetler",
                "267": "6. Diğer Maddi Olmayan Duran Varlıklar",
                "268": "7. Birikmiş Amortismanlar (-)",
                "269": "8. Verilen Avanslar",
            },
            "F. Özel Tükenmeye Tabi Varlıklar": {
                "271": "1. Arama Giderleri",
                "272": "2. Hazırlık ve Geliştirme Giderleri",
                "277": "3. Diğer Özel Tükenmeye Tabi Varlıklar",
                "278": "4. Birikmiş Tükenme Payları (-)",
                "279": "5. Verilen Avanslar",
            },
            "G. Gelecek Aylara Ait Giderler ve Gelir Tahakkukları": {
                "280": "1. Gelecek Yıllara Ait Giderler",
                "281": "2. Gelir Tahakkukları",
            },
            "H. Diğer Duran Varlıklar": {
                "291": "1. Gelecek Yıllarda İndirilecek KDV",
                "292": "2. Diğer KDV",
                "293": "3. Gelecek Yıllar İhtiyacı Stoklar",
                "294": "4. Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar",
                "295": "5. Peşin Ödenen Vergiler ve Fonlar",
                "297": "7. Diğer Çeşitli Duran Varlıklar",
                "296": "6. Geçici Hesap",
                "298": "8. Stok Değer Düşüklüğü Karşılığı (-)",
                "299": "9. Birikmiş Amortismanlar (-)"
            },
        },
    },
    "PASİF": {
        "III. Kısa Vadeli Yabancı Kaynaklar": {
            "A. Mali Borçlar": {
                "300": "1. Banka Kredileri",
                "301": "2. Finansal Kiralama İşlemlerinden Borçlar",
                "302": "3. Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)",
                "303": "4. Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri",
                "304": "5. Tahvil, Anapara, Borç, Taksit ve Faizleri",
                "305": "6. Çıkarılmış Bonolar ve Senetler",
                "306": "7. Çıkarılmış Diğer Menkul Kıymetler",
                "308": "8. Menkul Kıymetler İhraç Farkı (-)",
                "309": "9. Diğer Mali Borçlar",
            },
            "B. Ticari Borçlar": {
                "320": "1. Satıcılar",
                "321": "2. Borç Senetleri",
                "322": "3. Borç Senetleri Reeskontu (-)",
                "326": "4. Alınan Depozito ve Teminatlar",
                "329": "5. Diğer Ticari Borçlar",
            },
            "C. Diğer Borçlar": {
                "331": "1. Ortaklara Borçlar",
                "332": "2. İştiraklere Borçlar",
                "333": "3. Bağlı Ortaklıklara Borçlar",
                "335": "4. Personele Borçlar",
                "336": "5. Diğer Çeşitli Borçlar",
                "337": "6. Diğer Borç Senetleri Reeskontu (-)",
            },
            "D. Alınan Avanslar": {
                "340": "1. Alınan Sipariş Avansları",
                "349": "2. Alınan Diğer Avanslar",
            },
            "E. Yıllara Yaygın İnşaat ve Onarım Hakedişleri": {
                "350": "1. Yıllara Yaygın İnşaat ve Onarım Hakedişleri",
                "358": "2. Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı",
            },
            "F. Ödenecek Vergi ve Diğer Yükümlülükler": {
                "360": "1. Ödenecek Vergi ve Fonlar",
                "361": "2. Ödenecek Sosyal Güvenlik Kesintileri",
                "368": "3. Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler",
                "369": "4. Ödenecek Diğer Yükümlülükler",
            },
            "G. Borç ve Gider Karşılıkları": {
                "370": "1. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları",
                "371": "2. Dönem Karının Peşin Ödenen Vergi ve Yükümlülükleri (-)",
                "372": "3. Kıdem Tazminatı Karşılığı",
                "373": "4. Maliyet Giderleri Karşılığı",
                "379": "5. Diğer Borç ve Gider Karşılıkları",
            },
            "H. Gelecek Aylara Ait Gelirler ve Gider Tahakkukları": {
                "380": "1. Gelecek Aylara Ait Gelirler",
                "381": "2. Gider Tahakkukları",
            },
            "I. Diğer Kısa Vadeli Yabancı Kaynaklar": {
                "391": "1. Hesaplanan KDV",
                "392": "2. Diğer KDV",
                "393": "3. Merkez ve Şubeler Cari Hesabı",
                "397": "4. Sayım ve Tesellüm Fazlaları",
                "399": "5. Diğer Çeşitli Yabancı Kaynaklar",
            },
        },
        "IV. Uzun Vadeli Yabancı Kaynaklar": {
            "A. Mali Borçlar": {
                "400": "1. Banka Kredileri",
                "401": "2. Finansal Kiralama İşlemlerinden Borçlar",
                "402": "3. Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)",
                "405": "4. Çıkarılmış Tahviller",
                "407": "5. Çıkarılmış Diğer Menkul Kıymetler",
                "408": "6. Menkul Kıymetler İhraç Farkı (-)",
                "409": "7. Diğer Mali Borçlar",
            },
            "B. Ticari Borçlar": {
                "420": "1. Satıcılar",
                "421": "2. Borç Senetleri",
                "422": "3. Borç Senetleri Reeskontu (-)",
                "426": "4. Alınan Depozito ve Teminatlar",
                "429": "5. Diğer Ticari Borçlar",
            },
            "C. Diğer Borçlar": {
                "431": "1. Ortaklara Borçlar",
                "432": "2. İştiraklere Borçlar",
                "433": "3. Bağlı Ortaklıklara Borçlar",
                "436": "4. Diğer Çeşitli Borçlar",
                "437": "5. Diğer Borç Senetleri Reeskontu (-)",
                "438": "6. Kamuya Olan Ertelenmiş veya Taksitlendirilmiş Borçlar",
            },
            "D. Alınan Avanslar": {
                "440": "1. Alınan Sipariş Avansları",
                "449": "2. Alınan Diğer Avanslar",
            },
            "E. Borç ve Gider Karşılıkları": {
                "472": "1. Kıdem Tazminatı Karşılığı",
                "479": "2. Diğer Borç ve Gider Karşılıkları",
            },
            "F. Gelecek Yıllara Ait Gelirler ve Gider Tahakkukları": {
                "480": "1. Gelecek Yıllara Ait Gelirler",
                "481": "2. Gider Tahakkukları",
            },
            "G. Diğer Uzun Vadeli YAbancı Kaynaklar": {
                "492": "1. Gelecek Yıllara Ertelenen veya Terkin Edilen KDV",
                "493": "2. Tesise Katılma Payları",
                "499": "3. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar Toplamı",
            },
        },
        "V. Özkaynaklar": {
            "A. Ödenmiş Sermaye": {
                "500": "1. Sermaye",
                "501": "2. Ödenmemiş Sermaye (-)",
                "502": "3. Sermaye Düzeltmesi Olumlu Farkları",
                "503": "4. Sermaye Düzeltmesi Olumsuz Farkları(-)",
            },
            "B. Sermaye Yedekleri": {
                "520": "1. Hisse Senedi İhraç Primleri",
                "521": "2. Hisse Senedi İptal Karları",
                "522": "3. Maddi Duran Varlık Yeniden Değerleme Artışları",
                "523": "4. İştirakler Yeniden Değerleme Artışları",
                "524": "5. Diğer Sermaye Yedekleri",
                "525": "6. Kayda Alınan Emtia Özel Karşılık Hesabı",
                "529": "7. Demirbaş Makine ve Teçhizat Özel Karşılık Hesabı",
            },
            "C. Kar Yedekleri": {
                "540": "1. Yasal Yedekler",
                "541": "2. Statü Yedekleri",
                "542": "3. Olağanüstü Yedekler",
                "548": "4. Diğer Kar Yedekleri",
                "549": "5. Özel Fonlar",
            },
            "D. Geçmiş Yıl Karları": {
                "570": "1. Geçmiş Yıl Karları",
            },
            "E. Geçmiş Yıllar Zararları": {
                "580": "1. Geçmiş Yıllar Zararları (-)",
            },
            "F. Dönem Net Karı (zararı)": {
                "590": "1. Dönem Net Karı",
                "591": "2. Dönem Net Zararı (-)"
            },
        },
    },
}